---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "ClusterRoleBinding"
metadata:
  namespace: "site-certs"
  name: "site-certs-crb"
  labels: {}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "site-certs-cr"
subjects:
- kind: "ServiceAccount"
  name: "site-certs-sa"
  namespace: "site-certs"
