---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  namespace: "site-certs"
  name: "site-certs-rb"
  labels: {}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "site-certs-role"
subjects:
- kind: "ServiceAccount"
  name: "site-certs-sa"
  namespace: "site-certs"
