---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "Role"
metadata:
  namespace: "site-certs"
  name: "site-certs-role"
  labels: {}
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "patch"
