apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: site-certs
spec:
  validationFailureAction: audit
  rules:
  - name: clone-configmap
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: ConfigMap
      name: site-certs
      namespace: "{{request.object.metadata.name}}"
      synchronize : true
      clone:
        namespace: site-certs
        name: site-certs
  - name: mutate-pod
    match:
      resources:
        kinds:
        - Deployment
        selector:
          matchLabels:
            site-certs: do
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              containers:
              - (name): "*"
                volumeMounts:
                - name: site-certs
                  mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem 
                  subPath: ca-certificates.crt
                - name: site-certs
                  mountPath: /etc/ssl/certs/ca-certificates.crt 
                  subPath: ca-certificates.crt
                - name: site-certs
                  mountPath: /etc/ssl/certs/java/cacerts 
                  subPath: cacerts
                - name: site-certs
                  mountPath: /etc/pki/java/cacerts 
                  subPath: cacerts
                - name: site-certs
                  mountPath: /site-certs
              volumes:
              - name: site-certs
                configMap:
                  name: site-certs
