---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "ClusterRole"
metadata:
  name: "site-certs-cr"
  labels: {}
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "create"
  - "update"
  - "patch"
