apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: site-certs-cm
spec:
  validationFailureAction: audit
  rules:
  - name: clone-configmap
    match:
      resources:
        kinds:
        - Namespace
        selector:
          matchLabels:
            site-certs: do
    generate:
      kind: ConfigMap
      name: site-certs
      namespace: "{{request.object.metadata.name}}"
      synchronize : true
      clone:
        namespace: site-certs
        name: site-certs
